### ISSUE TITLE
Social media icon not working/Link error in code

### ISSUE THREAD

**Issue by bibek98231** [Sanjita90/Tour-Management-Project#11]
**Product:** All page
**Attachment:** 
![2](https://user-images.githubusercontent.com/64543701/118310763-bffb0200-b50e-11eb-8e1b-28f1c8f0a862.JPG)
**Steps to reproduce:** 
1) Open the page in the browser.
2) Go to the page bottom in the footer section.
3) You will see the social media icons on the right side of the page.
**Environment:** Opera Internet Browser
**Expected and Actual Result:**
 The icon should be able to redirect the user to social media accounts related to its related medias like Facebook icon to Facebook (if u are not creating Facebook page for it, than link it with its related matter or your personal account) but it is not working in all page.

**Comment by dhungana-bibek** [comment]
i have linked those icons to their sites.
