### ISSUE TITLE
Book now doesn’t work.

### ISSUE THREAD

**Issue by bibek98231** [Sanjita90/Tour-Management-Project#16]
**Product:** Home Page
**Attachment:** 
![Screenshot (498)](https://user-images.githubusercontent.com/64543701/118317814-3fd99a00-b518-11eb-917a-7b2e756d7bd2.png)

**Steps to reproduce:** 
1) Open the index page into browser.
2) Fill all the details.
3) Click Book now.
**Environment:** Opera Internet Browser
**Expected and Actual Result:**
After clicking book now, the user should be redirect to payment page or confirm the book through email.

**Comment by Shawshank-dulal** [comment]
Please check the html branch of the repository... there most of these issues have been resolved
