### ISSUE TITLE
Error message missing in login page (Email Id)

### ISSUE THREAD

**Issue by bibek98231** [Sanjita90/Tour-Management-Project#20]
**Product:** Login Page
**Attachment:**
![Screenshot (505)](https://user-images.githubusercontent.com/64543701/118390416-b1b3ff80-b64e-11eb-9a43-52640c550e53.png)
**Steps to Reproduce:**
1) Open the login file on the browser.
2) Fill the email without keeping @ sign.
**Environment:** Opera Internet Browser
**Expected and Actual Results:**
There should be error message showing while @ sign is missing in the Email ID section. Therefore, you should show a sign that indicates the problem of it.

**Comment by dhungana-bibek** [comment]
i have solved this problem, now it displays @is missing 
![Screenshot (116)](https://user-images.githubusercontent.com/80630264/118391050-0e64e980-b652-11eb-8bb6-dd67be4b4316.png)
