### ISSUE TITLE
Page Not Responsive

### ISSUE THREAD

**Issue by bibek98231** [Sanjita90/Tour-Management-Project#8]
**Attachment:**
![Screenshot (492)](https://user-images.githubusercontent.com/64543701/118264016-ca010e80-b4d6-11eb-9708-6b15cf5f1026.png)

 
**Step to reproduce:**
1) Open your browser.
2) Click right and you will see option for inspect element or press ctrl+shift+C .
3) Then select toogle device toolbar which is in left side of elements with a double square icon or simply press Ctrl+ Shift+ M.

**Expected:** 
While checking responsive , the page should be in order in every size we check.

**Comment by dhungana-bibek** [comment]
I have successfully fixed this issue and  now all of the pages are responsive in any devices.
![Screenshot (96)](https://user-images.githubusercontent.com/80630264/118266653-9fb15000-b4da-11eb-8019-d8172101a520.png)
