### ISSUE TITLE
Book now button is not working

### ISSUE THREAD

**Issue by bibek98231** [Sanjita90/Tour-Management-Project#9]
**Product**
 Destination Page
**Attachment**: 
![Screenshot (495)](https://user-images.githubusercontent.com/64543701/118310054-d05ead00-b50d-11eb-93c1-a5a403d47281.png)
**Steps to reproduce:**
1) Click the destination in the navbar.
2) After clicking, you will go to destination page.
3) Click in the Book now which is in the package description below.
**Environment**: Opera Internet Browser
**Expected and Actual Result:**
 After clicking Book Now, you should be able to take your user to book page or take the user to the further process to book that package but it is not working.

**Comment by dhungana-bibek** [comment]
i have already solved this problem as it is linked to the inquiry page where user can book their trip.
